import prompts from 'prompts';
import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs-extra';
import path from 'path';

export async function init() {
  console.log(chalk.bold('\n  Act SDK — Setup\n'));

  const answers = await prompts([
    {
      type: 'select',
      name: 'framework',
      message: 'What framework are you using?',
      choices: [
        { title: 'Next.js (App Router)', value: 'next-app' },
        { title: 'Next.js (Pages Router)', value: 'next-pages' },
        { title: 'React', value: 'react' },
      ],
    },
    {
      type: 'text',
      name: 'projectId',
      message: 'Project ID (from your Act dashboard):',
      initial: 'proj_',
    },
    {
      type: 'text',
      name: 'actionsPath',
      message: 'Where will your actions live?',
      initial: 'lib/actions.ts',
    },
  ]);

  const spinner = ora('Scaffolding Act SDK...').start();

  const cwd = process.cwd();

  // 1. Write act-sdk.config.ts
  await fs.outputFile(path.join(cwd, 'act-sdk.config.ts'), generateConfig(answers));

  // 2. Write example actions file
  await fs.outputFile(path.join(cwd, answers.actionsPath), generateActionsFile());

  // 3. Write .env.local entry
  const envPath = path.join(cwd, '.env.local');
  const envEntry = `\nNEXT_PUBLIC_ACT_API_KEY=your_api_key_here\n`;
  await fs.appendFile(envPath, envEntry);

  // 4. Write the provider wrapper based on framework
  if (answers.framework === 'next-app') {
    await fs.outputFile(path.join(cwd, 'app/act-provider.tsx'), generateProvider());
  }

  spinner.succeed('Act SDK scaffolded successfully!');

  console.log(chalk.dim('\n  Next steps:\n'));
  console.log(`  1. Add your API key to ${chalk.cyan('.env.local')}`);
  console.log(`  2. Wrap your actions in ${chalk.cyan(answers.actionsPath)}`);
  console.log(`  3. Run ${chalk.cyan('npx act-sdk generate')} to generate config`);
  console.log(`  4. Run ${chalk.cyan('npx act-sdk add chatbot')} to add the UI\n`);
}

function generateConfig(answers: { projectId: string; actionsPath: string }) {
  return `import { defineConfig } from "@act/core"

// Auto-generated by act-sdk generate
// Do not edit manually

export default defineConfig({
  apiKey: process.env.NEXT_PUBLIC_ACT_API_KEY!,
  projectId: "${answers.projectId}",
  description: "My application",
  actions: [],
  restrictedRoutes: [],
})
`;
}

function generateActionsFile() {
  return `import { createAct } from "@act/core"
import { z } from "zod"

export const act = createAct()

// Wrap your functions here
// Example:
export const exampleAction = act.action({
  id: "example_action",
  description: "An example action",
  input: z.object({
    message: z.string(),
  }),
})(async ({ message }) => {
  console.log(message)
})
`;
}

function generateProvider() {
  return `"use client"

import { ActProvider } from "@act/react"
import config from "@/act-sdk.config"
import { act } from "@/lib/actions"

export function Provider({ children }: { children: React.ReactNode }) {
  return (
    <ActProvider act={act} config={config}>
      {children}
    </ActProvider>
  )
}
`;
}
